# Generated by Django 6.0.2 on 2026-02-27 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('ramp', models.BooleanField(default=False)),
                ('elevator', models.BooleanField(default=False)),
                ('toilet', models.BooleanField(default=False)),
                ('average_rating', models.FloatField(default=0)),
                ('accessibility_score', models.IntegerField(default=0)),
            ],
        ),
    ]
