# Generated by Django 6.0.2 on 2026-02-27 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_userreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='accessibility_score',
        ),
        migrations.RemoveField(
            model_name='place',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='place',
            name='elevator',
        ),
        migrations.RemoveField(
            model_name='place',
            name='ramp',
        ),
        migrations.RemoveField(
            model_name='place',
            name='toilet',
        ),
        migrations.AddField(
            model_name='place',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='place',
            name='has_accessible_toilet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='place',
            name='has_elevator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='place',
            name='has_ramp',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='place',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
