# Generated by Django 6.0.2 on 2026-02-28 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_remove_place_accessibility_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='place',
            name='has_accessible_toilet',
        ),
        migrations.RemoveField(
            model_name='place',
            name='has_elevator',
        ),
        migrations.RemoveField(
            model_name='place',
            name='has_ramp',
        ),
        migrations.AddField(
            model_name='place',
            name='accessibility_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='place',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='place',
            name='elevator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='place',
            name='ramp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='place',
            name='toilet',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='place',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='UserReview',
        ),
    ]
