# Generated by Django 6.0.2 on 2026-02-28 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_remove_place_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='accessibility_score',
        ),
        migrations.RemoveField(
            model_name='place',
            name='elevator',
        ),
        migrations.RemoveField(
            model_name='place',
            name='ramp',
        ),
        migrations.RemoveField(
            model_name='place',
            name='toilet',
        ),
        migrations.AddField(
            model_name='place',
            name='has_accessible_toilet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='place',
            name='has_elevator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='place',
            name='has_ramp',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(blank=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='places.place')),
            ],
        ),
    ]
